### PR TITLE
Add imgui based gui example

### PR DESCRIPTION
**Pull request by bjorn3**
image

It looks much better with a ttf font instead of the builtin imgui font, but I will leave that for a future PR.

### CODE REVIEW

**Review by nbaksalyar — APPROVED** [review]
Looks great, thanks! Would you also like to add the font files?

macOS CI run fails with `the remote end hung up unexpectedly` which seems like a problem on the Travis's end. My vote is for ignoring this temporarily - there will be more PRs dealing with missing features for macOS anyway.

**Comment by bjorn3** [comment]
I will add a font tomorrow. The travis issue looks like a temporary network outage.

**Comment by bjorn3** [comment]
image

New screenshot with FiraMono as font.

**Comment by bjorn3** [comment]
```
---- target::linux::writemem::tests::write_memory_ptrace stdout ----

thread 'target::linux::writemem::tests::write_memory_ptrace' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EPERM)', src/target/linux/writemem.rs:292:91
```

I didn't change any of the relevant code, but there also doesn't seem to be a race-condition.

**Comment by nbaksalyar** [comment]
This seems like a bug in the ptrace tests. I will create a separate issue to tackle it, and I restarted the CI - let's see if it shows up consitently.

**Comment by bjorn3** [comment]
Happened again.

**Comment by nbaksalyar** [comment]
And now it's passed. I created #116 and will investigate it as a separate issue.
Merging this PR now.

Thanks!

**Pull request merged**
