### PR TITLE
Improve Readme

### PR DESCRIPTION
**Pull request by nbaksalyar**
[Rendered](https://github.com/nbaksalyar/headcrab/blob/improve-readme/README.md)

This adds a link to the website, information about backers & sponsors, and adds some information about using Headcrab to the top of the readme file.

### CODE REVIEW

**Comment by DeltaManiac** [comment]
Should we also add https://allcontributors.org/ too?

**Comment by nbaksalyar** [comment]
How does [it look now](https://github.com/nbaksalyar/headcrab/blob/improve-readme/README.md#contributing)?

**Review by bjorn3 — APPROVED** [review]

**Comment by DeltaManiac** [comment]
It looks Awesome 👏

**Comment by nbaksalyar** [comment]
Cheers!

**Pull request merged**
