### PR TITLE
Fix spelling in comments and variable names

### PR DESCRIPTION
**Pull request by hunger**
This makes my spellchecker happy, so that I can use it to avoid
adding more typos in the future:-)

### CODE REVIEW

**Comment by bjorn3** [comment]
First two commits LGTM. Re the third commit: I prefer mod.rs, as vscode otherwise puts it at the bottom of directory listing far away from the directory it's submodules are in.

**Comment by hunger** [comment]
@bjorn3 : I never use the file system tree for navigation, I just hit Ctrl-P and start typing. It is really annoying to have lots of mod.rs files then. I also prefer symbol.rs, target.rs, etc. in my list of open documents over having mod.rs in there several times.

**Comment by hunger** [comment]
I dropped the 3rd patch for now, running only with those that @bjorn3 was OK with:-) I will push the third one later separately.

**Comment by bjorn3** [comment]
Thanks!

**Pull request merged**
