### PR TITLE
remove _patch_breakpoint function

### PR DESCRIPTION
**Pull request by Arthamys**

### CODE REVIEW

**Comment by bjorn3** [comment]
Could you also change https://github.com/headcrab-rs/headcrab/blob/e4eb3f3b69050c8c89aad972168b500d1c7e108c/tests/test_utils.rs#L47 to use the new breakpoint support and remove the line at https://github.com/headcrab-rs/headcrab/blob/e4eb3f3b69050c8c89aad972168b500d1c7e108c/tests/testees/hello.rs#L7

**Comment by bjorn3** [comment]
You may need to change the amount of `single_step()` calls in some tests to adjust for the new instruction counts.

**Comment by Arthamys** [comment]
> remove the line at
> 
> https://github.com/headcrab-rs/headcrab/blob/e4eb3f3b69050c8c89aad972168b500d1c7e108c/tests/testees/hello.rs#L7

This should probably be kept, otherwise the compiler will just optimize away the function.
Or we can replace it by some other meaningless computation if you'd rather

**Comment by bjorn3** [comment]
You can keep it. I forgot that LLVM is smart enough to remove empty `#[inline(never)]` functions.

**Review by nbaksalyar — APPROVED** [review]
This looks good, thanks! Could you please rebase it on latest master so that it can be merged?

**Comment by Arthamys** [comment]
The checks failed due to #116

**Comment by bjorn3** [comment]
Thanks!

**Pull request merged**
